version: '3.3'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - devdojo_data:/var/lib/mysql

volumes:
  devdojo_data: